
"use strict";

// https://alloyteam.github.io/eslint-config-alloy/
module.exports = {
  "extends": require.resolve("eslint-config-react-app"),
  "rules": {
    'no-restricted-globals': "off",
    "no-unused-vars": "off",
    "eqeqeq": "off",
    "new-parens": "off",
    "no-mixed-operators": "off",
    "no-multi-assign": "off",
    "no-lonely-if": "off",
    "no-inline-comments": "off",
    "no-continue": "off",
    "newline-per-chained-call": "off",
    "no-array-constructor": "off",
    "no-bitwise": "off",
    "no-mixed-spaces-and-tabs": "off",
    "no-multiple-empty-lines": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-new-object": "warn",
    "no-restricted-syntax": "off",
    "no-tabs": "off",
    "no-ternary": "off",
    "no-trailing-spaces": "off",
    "no-underscore-dangle": "off",
    "no-unneeded-ternary": "off",
    "no-whitespace-before-property": "warn",
    "nonblock-statement-body-position": "off",
    "object-curly-newline": "off",
    "object-curly-spacing": "off",
    "object-property-newline": "off",
    "one-var": "off",
    "no-new-func": "off",
    "default-case": "off",
    "no-self-compare": "off",
    "no-fallthrough": "off",
    "prefer-numeric-literals": "off",
    "no-useless-concat": "off",
    "strict": "off",
    "no-lone-blocks": "off",
    "no-labels": "off",
    "no-useless-escape": "off",
    "no-control-regex": "off",
    "no-unused-expressions": "off",
    "no-script-url": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "no-template-curly-in-string": "off",
    "jsx-a11y/alt-text": "off"
  }
};